### ISSUE TITLE
Error while typing in Output window

### ISSUE THREAD

**Issue by manoj-apare** [bbeversdorf/vscode-drupal-check#3]
While typing it opens Output window with following error:

[Error - 2:51:07 PM] Request textDocument/completion failed.
  Message: Unhandled method textDocument/completion
  Code: -32601 
Issues found.

<img width="1104" alt="Screen Shot 2019-10-21 at 2 53 43 PM" src="https://user-images.githubusercontent.com/6881443/67193258-a49f4200-f412-11e9-8f6a-06d36ba11bfa.png">

**Comment by bbeversdorf** [comment]
This was caused by one of the dependencies I was using. I've updated and havent seen the issue. (Hopefully this is fixed)
