### ISSUE TITLE
How to generate depredations for entire custom module folder in Drupal? 

### ISSUE THREAD

**Issue by iyyappandrupal** [bbeversdorf/vscode-drupal-check#8]
How to generate depredations for entire custom module folder in Drupal?

**Comment by bbeversdorf** [comment]
This extension highlights deprecated code found by [drupal-check](https://github.com/mglaman/drupal-check). In order for you to check directories install drupal-check and with the directory specified with the run command [[Source]](https://github.com/mglaman/drupal-check#2-run-drupal-check).
